version: '3'

services:
  web:
    build: .
    container_name: mimiw-portfolio
    ports:
      - "8080:80"
    # ðŸ‘‡ à¹€à¸žà¸´à¹ˆà¸¡à¸ªà¹ˆà¸§à¸™à¸™à¸µà¹‰à¹€à¸‚à¹‰à¸²à¸¡à¸²à¸„à¸£à¸±à¸š
    volumes:
      - .:/usr/share/nginx/html